### ISSUE TITLE
error: ‘class pj::Endpoint’ has no member named ‘codecEnum’; did you mean ‘codecEnum2’?

### ISSUE THREAD

**Issue by mariarti** [Infactum/tg2sip#25]
trying to build on Ubuntu 18.04 LTS with recommended  versions and got

`
/root/tg2sip/tg2sip/sip.cpp: In static member function ‘static void sip::Client::init_pj_endpoint(Settings&, sip::LogWriter*)’:
/root/tg2sip/tg2sip/sip.cpp:188:38: error: ‘class pj::Endpoint’ has no member named ‘codecEnum’; did you mean ‘codecEnum2’?
     CodecInfoVector codecVector = ep.codecEnum();
                                      ^~~~~~~~~
                                      codecEnum2
`
![Screenshot from 2020-04-20 15-43-39](https://user-images.githubusercontent.com/1933140/79758481-fd419000-830c-11ea-9d8c-e81596b3eb97.png)

**Comment by Infactum** [comment]
Most probably you are building with newer pjproject version which has changed some API.
Please try [this](https://github.com/Infactum/pjproject) fork.

**Comment by mariarti** [comment]
@Infactum thanks a lot for advise!
It passed now to 100%, but finished with other error:
`[100%] Linking CXX executable tg2sip
/usr/bin/ld: cannot open output file tg2sip: Is a directory
collect2: error: ld returned 1 exit status
CMakeFiles/tg2sip.dir/build.make:261: recipe for target 'tg2sip' failed
make[2]: *** [tg2sip] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/tg2sip.dir/all' failed
make[1]: *** [CMakeFiles/tg2sip.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

Just to be sure, I've cloned it to directory named with another name as tg2sip, but same error.

**Comment by Infactum** [comment]
Working build instructions can be found inside [appveyor.yml](https://github.com/Infactum/tg2sip/blob/master/appveyor.yml) and [buildenv](https://github.com/Infactum/tg2sip/tree/master/buildenv).

**Comment by mariarti** [comment]
Thanks for advice
problem was solved by correct directory path (before I should create directory build and enter it)

mkdir build && cd build;
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig && cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build .
