### ISSUE TITLE
Compilation error. pjproject 2.10

### ISSUE THREAD

**Issue by wzooroo** [Infactum/tg2sip#35]
Compilation error. pjproject 2.10

`[ 97%] Building CXX object CMakeFiles/tg2sip.dir/tg2sip/main.cpp.o
[ 98%] Building CXX object CMakeFiles/tg2sip.dir/tg2sip/tg.cpp.o
[ 98%] Building CXX object CMakeFiles/tg2sip.dir/tg2sip/sip.cpp.o
/usr/src/tg2sip/tg2sip/sip.cpp: In static member function ‘static void sip::Client::init_pj_endpoint(Settings&, sip::LogWriter*)’:
/usr/src/tg2sip/tg2sip/sip.cpp:188:38: error: ‘class pj::Endpoint’ has no member named ‘codecEnum’; did you mean ‘codecEnum2’?
     CodecInfoVector codecVector = ep.codecEnum();
                                      ^~~~~~~~~
                                      codecEnum2
gmake[2]: *** [CMakeFiles/tg2sip.dir/tg2sip/sip.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/tg2sip.dir/all] Error 2
gmake: *** [all] Error 2`

**Comment by Infactum** [comment]
Currently tg2sip is compiled againist pjproject 2.9

**Comment by radicaldrew** [comment]
> Currently tg2sip is compiled againist pjproject 2.9

I have it working fine with pjproject 2.9
I am getting distorted voice on one of the end of the call though.
I was even able to upgrade libtgvoip to the latest version but still have the distortion
I tried direct as well as through pbx.
Any ideas. and do you want the updated libtgvoip changes?

**Comment by tg2sipfork** [comment]
> did you mean ‘codecEnum2



change it to 

```
‘class pj::Endpoint’ has no member named ‘codecEnum’; did you mean ‘codecEnum2’

codecEnum2

```

**Comment by razametal** [comment]
> nevermind I never updated confg_site.h once I did that call works great!
> 
> > Currently tg2sip is compiled againist pjproject 2.9
> 
> I have it working fine with pjproject 2.9 I am getting distorted voice on one of the end of the call though. I was even able to upgrade libtgvoip to the latest version but still have the distortion I tried direct as well as through pbx. Any ideas. and do you want the updated libtgvoip changes?

I'm having the same issue with tg2sip compiled with pjproject 2.9, distorted voice on the telegram client side (latest android and iphone versions). Have you any idea on how to fix it?
